#!/bin/bash

error=0

if [ -z "${ZSH_VERSION:-}" ]; then
  test_root="$(readlink -f $(dirname "${BASH_SOURCE[0]}"))"
else
  test_root="$(readlink -f $(dirname "${(%):-%N}"))"
fi

test_exec="${test_root}/test"
export HOME="${test_root}/home"

echo "Running $SHELL tests (interactive) ..."
"$SHELL" -i "${test_exec}" || error=1

echo "Running $SHELL tests (non-interactive) ..."
"$SHELL" "${test_exec}" || error=1

exit "$error"
