#!/bin/bash

test_root=`dirname "${BASH_SOURCE[0]-$0}"`
test_root=`cd "$test_root" && pwd`

export CHPHAROS_ROOT="${test_root}/test-binaries"
mkdir -p "${CHPHAROS_ROOT}"

if [ -z "$CHPHAROS_TOKEN" ]; then
  printf "Warn: Some tests may fail. If CHPHAROS_TOKEN or CHPHAROS_USER and CHPHAROS_PASS are not set and valid."
fi

[ -f "${CHPHAROS_ROOT}/versions/1.0.0/pharos-cluster" ] && \
  [ -f "${CHPHAROS_ROOT}/versions/1.0.0/kubectl" ] && \
  [ -f "${CHPHAROS_ROOT}/versions/1.2.2/pharos-cluster" ] && \
  [ -f "${CHPHAROS_ROOT}/versions/1.2.2/kubectl" ] &&
  echo "Already installed test binaries" && \
  exit 0

. "${test_root}"/../share/chpharos/chpharos.sh

if [ -z "$CHPHAROS_TOKEN" ] && [ ! -z "$CHPHAROS_USER" ] && [ ! -z "$CHPHAROS_PASS" ]; then
  chpharos login --username $CHPHAROS_USER --password $CHPHAROS_PASS
fi

echo "Listing available versions:"
chpharos list-remote

echo "OS: $(_chpharos_os) CPU: $(_chpharos_cpu)"

chpharos install 1.0.0
chpharos install 1.2.2
chpharos reset
