sudo: false
os:
- linux
- osx
language: generic
addons:
  apt:
    packages:
    - shunit2
    - zsh
    - curl
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shunit2 bash zsh curl; fi
before_script:
- export SHUNIT2="$(command -v shunit2 2>/dev/null)"
script: make test
env:
  global:
    secure: cgdWLix2l5e7DVXr2zws9o5FJJMIYEEBfZO2cOKmrCwR3jBYKctbi0S3yj28sn9IWsPuHJ/nrAL0N/96AMRE+nsDNIsb6+hs0aEQLa37l/oc9+GNqmvIxu6uTEl/kF64eS0e3ztJ4VFH4DhHOrpbSBEc/drsiVS4ZWsnDnm1Wtbca0qaxPOM8cAZCvgSQ53aif80nqLG22WgZZf/5ga1bV0CEligNYKGkfApD6hr2NzC8UC1dmnCtPpieckV65E+89AJWx0up2T9P7fEDVudcyGe5OUNp7G+lXI1E7UH+v9SsiZg3tu4phhepVRTwegme82pV7aRGA/KLLs90JHzlVsN83cibo8nif+N7RcPBkn8qi8dE+MPcrLT7+q0p5bqaa2d2wZNakSAxFGzeNNm7oaFZKOOztuqweq/S1bsKz58JfRAOQZo66bRhQa5pG9ejRH/2DPkM9lk+TLmkqdasvXKlFWUQa8NN17dJutai5MjYFGDYvR6Vqx8SghPj2/+HxGgHMUYSQAW4U0/B8x6sDg21RG36QDlQChyAFhQsUWno7OTFV4UjEFQz3WDdQxSQOJp/fQnd0zDVVBTwJBRcV9JdnX8WW1bPjjq5czxU0d69pa/6XqkyLUJ9LstKM6tMPw3xl/ZIxICfmQQ9Ge6wk+bIPWpt75C2b0p/L6wc0Y=
branches:
  only:
  - master
