sudo: false

os:
  - linux
  - osx

language: generic

addons:
  apt:
    packages:
      - shunit2
      - zsh
      - curl

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shunit2 bash zsh curl; fi

before_script:
  - export SHUNIT2="$(command -v shunit2 2>/dev/null)"

script: make test
